Bumping packages to fix build and security issues
open-telemetry/opentelemetry-network pull request #275
Opened 2024-09-12 08:59 UTC by jakub-racek-swi

**Description:** Bumping packages to fix build and security issues - this is accompanied by a PR to the build env:

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2024-09-18 07:21 UTC, gantrior requested changes

2024-09-18 07:21 UTC, gantrior commented on .github/workflows/build-and-test.yaml
> +  BENV_IMAGE: public.ecr.aws/u7d6c4a3/solarwinds-opentelemetry-network:build-env
I believe you should move PR to draft if you are still experimenting with the changes. We shouldn't merge to upstream use of image from solarwinds owned registry

2024-09-23 15:30 UTC, jakub-racek-swi commented
Hey @yonch, I was taking another look at the failing unit tests in my otel-network build. 

I've made some progress with investigating the abseil failures, which is most likely related to some old issue that happens when asan is not applied to the entire build (https://github.com/abseil/abseil-cpp/issues/1524). 

While investigating the 'render_test', I was trying to start the unit tests locally, but got wildly different test results.
```
The following tests FAILED:
          1 - render_test (Failed)
          9 - json_test (SEGFAULT)
         10 - fixed_hash_test (SEGFAULT)
         13 - log_modifiers_test (SEGFAULT)
         19 - bits_test (SEGFAULT)
         20 - counter_test (SEGFAULT)
         21 - counter_to_rate_test (SEGFAULT)
         25 - cgroup_handler_test (SEGFAULT)
         26 - kernel_symbols_test (Failed)
```
I am wondering how come the unit tests produce different results here in the github actions and when built locally on my machine. This is only with asan, however, as all tests do pass in the regular build.

I also wanted to ask how to handle debugging, since there is a `--debug` option in the build script. How do I set it up? Couldn't find any info in the docs sadly (though I could just be bad at navigating them :))

2024-09-23 19:26 UTC, yonch commented
Hi @jakub-racek-swi !

I'm not sure regarding the ASAN failures. What CPU are you running on?

Let me check the debug builds. I remember we used to have a script to run under gdb..

2024-09-23 19:37 UTC, yonch commented
So for debugging the kernel collector:

- Here is the docker [build clause](https://github.com/open-telemetry/opentelemetry-network/blob/71fe60b01c00a6b162773e09575dcaf542793c3f/collector/kernel/CMakeLists.txt#L229) for kernel-collector debug builds.
- Setting the environment variable `EBPF_NET_RUN_UNDER_GDB=gdb` might get you what you want (from [entrypoint.sh](https://github.com/open-telemetry/opentelemetry-network/blob/71fe60b01c00a6b162773e09575dcaf542793c3f/collector/kernel/entrypoint.sh#L75) ).
- If you're using the devbox scripts, the kernel collector's [supports a `--gdb` flag](https://github.com/open-telemetry/opentelemetry-network/blob/71fe60b01c00a6b162773e09575dcaf542793c3f/dev/devbox/source/kernel-collector.sh#L79)

Hope this is what you're looking for..

2024-10-09 19:06 UTC, yonch commented
Verified that this PR compiles with the new build image. 👍 

My test run with `./build.sh --asan --debug test` yields:
```
The following tests FAILED:
	  1 - render_test (Failed)
	 10 - fixed_hash_test (Failed)
	 26 - kernel_symbols_test (Failed)
```
I didn't get the SEGFAULTs you got -- maybe you changed something since that earlier post?

Without ASAN tests seem to pass.

2024-11-26 19:52 UTC, yonch commented
@jakub-racek-swi the new build image is `docker.io/otel/opentelemetry-network-build-tools`. It is built via GitHub Actions on the build tools repo.

Are you comfortable changing `.github/workflows/build-and-test.yaml` to use that image, and mark the PR ready for review?

2025-01-07 18:38 UTC, merged

2025-01-07 22:56 UTC, yonch commented
@jakub-racek-swi Github auto-closed the PR when I merged #286. Hope you are well and thank you for the contribution!